name: IT Goof
markdown: kramdown
exclude: [vendor]
future: true  #LACKING THIS WAS WHY A LOT OF PAGES WERENT BEING GENERATED, THEY HAD DATES GREATER THAN THE CURRENT DATE!!!
relative_permalinks: false 

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  projects:
    output: true
    godot:
      output: true
  posts:
    output: true
    permalink: /:year/:month/:day/:title/